# Generated by Django 3.1.2 on 2022-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artxiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_statement', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('first_name', models.CharField(max_length=20, verbose_name='First name')),
                ('family_name', models.CharField(max_length=20, verbose_name='Family name')),
                ('abstract', models.CharField(max_length=200, verbose_name='Abstract')),
                ('exhibition_histry', models.CharField(max_length=200, verbose_name='Exhibition histry')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Post day')),
            ],
        ),
    ]
