# Generated by Django 3.1.2 on 2022-08-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artxivs', '0002_auto_20220805_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artxiv',
            name='artist_statement',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
